CREATE TABLE `pricingAdministration` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`scenarioName` varchar(255) NOT NULL,
	`planName` varchar(255) NOT NULL,
	`sourceType` enum('public','internal') NOT NULL DEFAULT 'internal',
	`costPeriod` enum('monthly','annual','custom') NOT NULL DEFAULT 'annual',
	`sourceCurrency` varchar(3) NOT NULL DEFAULT 'USD',
	`listUnitCost` decimal(14,4) NOT NULL,
	`negotiatedUnitCost` decimal(14,4),
	`useNegotiatedCost` boolean NOT NULL DEFAULT false,
	`quantity` int NOT NULL DEFAULT 1,
	`periodMonths` int NOT NULL DEFAULT 12,
	`dealDiscountRate` decimal(8,4) NOT NULL DEFAULT '0',
	`exchangeRate` decimal(14,6) NOT NULL,
	`exchangeSpreadRate` decimal(8,4) NOT NULL DEFAULT '0',
	`manufacturerAbsorbsIrrf` boolean NOT NULL DEFAULT true,
	`irrfRate` decimal(8,4) NOT NULL DEFAULT '0',
	`cideRate` decimal(8,4) NOT NULL DEFAULT '0',
	`pisRate` decimal(8,4) NOT NULL DEFAULT '0',
	`cofinsRate` decimal(8,4) NOT NULL DEFAULT '0',
	`issRate` decimal(8,4) NOT NULL DEFAULT '0',
	`iofRate` decimal(8,4) NOT NULL DEFAULT '0',
	`otherTaxRate` decimal(8,4) NOT NULL DEFAULT '0',
	`financialCostRate` decimal(8,4) NOT NULL DEFAULT '0',
	`operationalCostRate` decimal(8,4) NOT NULL DEFAULT '0',
	`contingencyRate` decimal(8,4) NOT NULL DEFAULT '0',
	`minimumMarginRate` decimal(8,4) NOT NULL DEFAULT '25',
	`targetMarginRate` decimal(8,4) NOT NULL DEFAULT '30',
	`manualSalePriceBrl` decimal(14,2),
	`grossForeignCost` decimal(14,2),
	`netForeignCost` decimal(14,2),
	`baseCostBrl` decimal(14,2),
	`taxesBrl` decimal(14,2),
	`totalCostBrl` decimal(14,2),
	`minimumPriceBrl` decimal(14,2),
	`suggestedPriceBrl` decimal(14,2),
	`finalSalePriceBrl` decimal(14,2),
	`unitSalePriceBrl` decimal(14,2),
	`contributionBrl` decimal(14,2),
	`contributionRate` decimal(8,4),
	`markupRate` decimal(8,4),
	`status` enum('draft','in_review','approved','published','withdrawn') NOT NULL DEFAULT 'draft',
	`productPriceId` int,
	`publicPlanName` varchar(255),
	`publicBillingPeriod` enum('monthly','annual','custom') NOT NULL DEFAULT 'annual',
	`publicMinSeats` int NOT NULL DEFAULT 1,
	`publicMaxSeats` int,
	`publicDescription` text,
	`sourceLabel` varchar(255),
	`sourceUrl` varchar(1000),
	`notes` text,
	`createdByUserId` int NOT NULL,
	`approvedByUserId` int,
	`approvedAt` timestamp,
	`publishedAt` timestamp,
	`withdrawnAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pricingAdministration_id` PRIMARY KEY(`id`)
);
